---
- name: Ensure Nginx repo is present and enabled
  copy:
    src: etc/yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  tags: [ 'nginx' ]

- name: Ensure Nginx is installed
  yum:
    name: nginx
    state: installed
  tags: [ 'nginx' ]

- name: Template root Nginx config
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags: [ 'nginx' ]

- name: Ensure Nginx is started
  service:
    name: nginx
    enabled: yes
    state: started
  tags: [ 'nginx' ]

- name: Set up PHP upstreams
  template:
    src: etc/nginx/conf.d/upstream.conf
    dest: /etc/nginx/conf.d/upstream.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: [ 'nginx' ]