---
- name: Create install location for WP-CLI
  file:
    dest: /usr/share/wp-cli
    mode: 0755
    owner: root
    group: root
    state: directory
  tags: [ 'wp-cli' ]

- name: Install WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/share/wp-cli/wp
    mode: 0755
    owner: root
    group: root
  tags: [ 'wp-cli' ]

- name: Symlink WP-CLI
  file:
    dest: /usr/local/bin/wp
    src: /usr/share/wp-cli/wp
    state: link
  tags: [ 'wp-cli' ]
