---
- hosts: all
  connection: local
  become: yes
  become_user: root

  roles:
    - common
    - nginx
    - remi
    - php
    - mariadb
    - memcached
    - wp-cli
    # - admin
    # - xhprof

# 